import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("합: ", np.sum(arr))
print("행의 원소 합: ", np.sum(arr, axis=0))
print("열의 원소 합: ", np.sum(arr, axis=1))
print("평균: ", np.mean(arr))
print("행의 원소 평균: ", np.mean(arr, axis=0))
print("열의 원소 평균: ", np.mean(arr, axis=1))
print("최대: ", np.max(arr))
print("최소: ", np.min(arr))
print("행의 원소 최대값: ", np.max(arr, axis=0))
print("행의 원소 최소값: ", np.min(arr, axis=0))
print("열의 원소 최대값: ", np.max(arr, axis=1))
print("열의 원소 최소값: ", np.min(arr, axis=1))
print(np.argmax(arr))
print(np.argmin(arr))